export const FETCH_PEOPLE_REQUEST = "FETCH_PEOPLE_REQUEST";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const FETCH_PEOPLE_ERROR = "FETCH_PEOPLE_ERROR";
export const FILTER_MALE = "FILTER_MALE";
export const FILTER_FEMALE = "FILTER_FEMALE";
export const FILTER_AGE = "FILTER_AGE";
export const FILTER_NAME = "FILTER_NAME";
export const FILTER_LASTNAME = "FILTER_LASTNAME";
